# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{perfectsched}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sadayuki Furuhashi"]
  s.date = %q{2011-08-30}
  s.default_executable = %q{perfectsched}
  s.email = %q{frsyuki@gmail.com}
  s.executables = ["perfectsched"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "bin/perfectsched",
     "lib/perfectsched.rb",
     "lib/perfectsched/backend.rb",
     "lib/perfectsched/backend/rdb.rb",
     "lib/perfectsched/backend/simpledb.rb",
     "lib/perfectsched/command/perfectsched.rb",
     "lib/perfectsched/croncalc.rb",
     "lib/perfectsched/engine.rb",
     "lib/perfectsched/version.rb"
  ]
  s.homepage = %q{https://github.com/treasure-data/perfectsched}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Highly available distributed cron built on RDBMS or SimpleDB}
  s.test_files = [
    "test/backend_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cron-spec>, ["= 0.1.2"])
      s.add_runtime_dependency(%q<sequel>, ["~> 3.26.0"])
      s.add_runtime_dependency(%q<aws-sdk>, ["~> 1.1.1"])
      s.add_runtime_dependency(%q<perfectqueue>, ["~> 0.7.0"])
    else
      s.add_dependency(%q<cron-spec>, ["= 0.1.2"])
      s.add_dependency(%q<sequel>, ["~> 3.26.0"])
      s.add_dependency(%q<aws-sdk>, ["~> 1.1.1"])
      s.add_dependency(%q<perfectqueue>, ["~> 0.7.0"])
    end
  else
    s.add_dependency(%q<cron-spec>, ["= 0.1.2"])
    s.add_dependency(%q<sequel>, ["~> 3.26.0"])
    s.add_dependency(%q<aws-sdk>, ["~> 1.1.1"])
    s.add_dependency(%q<perfectqueue>, ["~> 0.7.0"])
  end
end

